### ISSUE TITLE
"save" option

### ISSUE THREAD

**Issue by brscag10** [daniellacosse/idea-slot-machine#2]
Might be cool to have a way to save a set you particularly like.

**Comment by daniellacosse** [comment]
ah, so, fun rule of thumb about software that isn't readily apparent, as soon as you allow a user to write something, things get 10x more complicated because now you have to store and maintain what everybody's written down somehow, and then you have to make sure that each person can't see the other person's stuff.

but I have a solution! basically, we can use the browser's `localStorage` to do this, effectively storing the spins in browser itself. the downside being, if the user ever clears their browser history, or switches to a different browser, they'll lose their saved spins - but this avoid all the complexity of maintaining a centralized database and authentication system!
